package dev.vital.quester;

public enum QuestList {
    TUTORIAL_ISLAND,
    COOKS_ASSISTANT,
    SHEEP_SHEARER,
    THE_RESTLESS_GHOST,
    RUNE_MYSTERIES,
    X_MARKS_THE_SPOT,
    PIRATES_TREASURE,
    ROMEO_AND_JULIET
}
